[[headers]]
  for = "/dist/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/dist/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
